# This is a basic workflow to help you get started with Actions

name: Exercicio de python

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    environment: exercicio
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      # Run python script with environment variables
      - name: Run python script
        env:
          DB: ${{ vars.DB }}
          USER_PG: ${{ secrets.USER_PG }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          python exercicio.py

